### PR TITLE
Add EditorRowGridTitleFollowing

### PR DESCRIPTION
**Pull request by itagagaki**
Added EditorRowGridTitleFollowing to add space between hostname and port or serial port and speed.

RDP port field width to match others.

### CODE REVIEW

**Comment by majkinetor** [comment]
Screenshot ?

**Comment by itagagaki** [comment]
RemoteApp and others: Before:
remoteapp-before

You can see ポート番号 (Port) is attached to the left text box without a gap.

After:
remoteapp-after

RDP: Before:
rdp-before

The width of ポート番号 (Port) is wider than others. Only the RDP was so.

After:
rdp-after

**Comment by majkinetor** [comment]
Must be i18n thing:

Here is mine:

image

**Comment by majkinetor** [comment]
So, now we need screens with english language.

**Comment by majkinetor** [comment]
And I know that @VShawn doesn't seem very interested in normalizing language here, but its contraproductive for sure. 

Since you are doing those PRs (thanks a lot BTW), you should provide any artifacts on English unless the thing is about i18n (like this might be the case), in which case we need to check how UI looks on main language besides the other one.

**Comment by itagagaki** [comment]
Of course, I always check in English.

The issue is that when we have a side-by-side layout of `EditorRowGridTitle`, it sticks. There should be an appropriate gap, or margin, but it is zero. So I added `EditorRowGridTitleFollowing` style to apply it to the second and subsequent ones that are side-by-side.

For English, Before:
image

After:
image

I've shown the example on the Japanese screen because it's easy to see the problem at a glance, but whether it's English or any other language, you'll face this problem if the text fills the title box.

e.g.

Before:
image

After:
en-long-after

**Comment by itagagaki** [comment]
Before the fix, the layout was as follows. The blue boxes are for the title text. They have a 30px margin on the right, but no margin on the left.
The text in the blue box is right-aligned, so if the text is short, it will have a margin on the left, but if the text fills the box, there will be no space between it and the elements on the left.

image

So I simply added a 20px margin to the left of text boxes such as Port as well.

**Comment by VShawn** [comment]
> And I know that @VShawn doesn't seem very interested in normalizing language here

Ahaha, you got me, and @itagagaki has made significant contributions to the standardization

> if the text fills the box, there will be no space between it and the elements on the left.

👍 isee, there might be same issue elsewhere. especially the styling code I completed in `PRemoteM` was all designed with english width.

**Pull request merged**
